module.exports = [
    "Abilene Christian University (TX)"
    "Abraham Baldwin Agricultural College (GA)"
    "Academy of Art University (CA)"
    "Acadia University (None)"
    "Adams State University (CO)"
    "Adelphi University (NY)"
    "Adrian College (MI)"
    "Adventist University of Health Sciences (FL)"
    "Agnes Scott College (GA)"
    "AIB College of Business (IA)"
    "Alabama Agricultural and Mechanical University (AL)"
    "Alabama State University (AL)"
    "Alaska Pacific University (AK)"
    "Albany College of Pharmacy and Health Sciences (NY)"
    "Albany State University (GA)"
    "Albertus Magnus College (CT)"
    "Albion College (MI)"
    "Albright College (PA)"
    "Alcorn State University (MS)"
    "Alderson Broaddus University (WV)"
    "Alfred University (NY)"
    "Alice Lloyd College (KY)"
    "Allegheny College (PA)"
    "Allen College (IA)"
    "Allen University (SC)"
    "Alliant International University (CA)"
    "Alma College (MI)"
    "Alvernia University (PA)"
    "Alverno College (WI)"
    "Amberton University (TX)"
    "American Academy of Art (IL)"
    "American Indian College of the Assemblies of God (AZ)"
    "American InterContinental University (IL)"
    "American International College (MA)"
    "American Jewish University (CA)"
    "American Public University System (WV)"
    "American University (DC)"
    "American University in Bulgaria (None)"
    "American University in Cairo (None)"
    "American University of Beirut (None)"
    "American University of Paris (None)"
    "American University of Puerto Rico (PR)"
    "Amherst College (MA)"
    "Amridge University (AL)"
    "Anderson University (IN)"
    "Anderson University (SC)"
    "Andrews University (MI)"
    "Angelo State University (TX)"
    "Anna Maria College (MA)"
    "Antioch University (OH)"
    "Appalachian Bible College (WV)"
    "Appalachian State University (NC)"
    "Aquinas College (MI)"
    "Aquinas College (TN)"
    "Arcadia University (PA)"
    "Argosy University (CA)"
    "Arizona Christian University (AZ)"
    "Arizona State University (AZ)"
    "Arizona State University - West (AZ)"
    "Arkansas Baptist College (AR)"
    "Arkansas State University (AR)"
    "Arkansas Tech University (AR)"
    "Armstrong Atlantic State University (GA)"
    "Art Academy of Cincinnati (OH)"
    "Art Center College of Design (CA)"
    "Art Institute of Atlanta (GA)"
    "Art Institute of Colorado (CO)"
    "Art Institute of Houston (TX)"
    "Art Institute of Pittsburgh (PA)"
    "Art Institute of Portland (OR)"
    "Art Institute of Seattle (WA)"
    "Asbury University (KY)"
    "Ashford University (IA)"
    "Ashland University (OH)"
    "Assumption College (MA)"
    "Athens State University (AL)"
    "Auburn University (AL)"
    "Auburn University - Montgomery (AL)"
    "Augsburg College (MN)"
    "Augustana College (IL)"
    "Augustana College (SD)"
    "Aurora University (IL)"
    "Austin College (TX)"
    "Austin Peay State University (TN)"
    "Ave Maria University (FL)"
    "Averett University (VA)"
    "Avila University (MO)"
    "Azusa Pacific University (CA)"
    "Babson College (MA)"
    "Bacone College (OK)"
    "Baker College of Flint (MI)"
    "Baker University (KS)"
    "Baldwin Wallace University (OH)"
    "Ball State University (IN)"
    "Baptist Bible College (MO)"
    "Baptist Bible College and Seminary (PA)"
    "Baptist College of Florida (FL)"
    "Baptist Memorial College of Health Sciences (TN)"
    "Baptist Missionary Association Theological Seminary (TX)"
    "Bard College (NY)"
    "Bard College at Simon's Rock (MA)"
    "Barnard College (NY)"
    "Barry University (FL)"
    "Barton College (NC)"
    "Bastyr University (WA)"
    "Bates College (ME)"
    "Bauder College (GA)"
    "Bay Path College (MA)"
    "Bay State College (MA)"
    "Bayamon Central University (PR)"
    "Baylor University (TX)"
    "Beacon College (FL)"
    "Becker College (MA)"
    "Belhaven University (MS)"
    "Bellarmine University (KY)"
    "Bellevue College (WA)"
    "Bellevue University (NE)"
    "Bellin College (WI)"
    "Belmont Abbey College (NC)"
    "Belmont University (TN)"
    "Beloit College (WI)"
    "Bemidji State University (MN)"
    "Benedict College (SC)"
    "Benedictine College (KS)"
    "Benedictine University (IL)"
    "Benjamin Franklin Institute of Technology (MA)"
    "Bennett College (NC)"
    "Bennington College (VT)"
    "Bentley University (MA)"
    "Berea College (KY)"
    "Berkeley College (NJ)"
    "Berkeley College (NY)"
    "Berklee College of Music (MA)"
    "Berry College (GA)"
    "Bethany College (KS)"
    "Bethany College (WV)"
    "Bethany Lutheran College (MN)"
    "Bethel College (IN)"
    "Bethel College (KS)"
    "Bethel University (TN)"
    "Bethel University (MN)"
    "Bethune-Cookman University (FL)"
    "BI Norwegian Business School (None)"
    "Binghamton University - SUNY (NY)"
    "Biola University (CA)"
    "Birmingham-Southern College (AL)"
    "Bismarck State College (ND)"
    "Black Hills State University (SD)"
    "Blackburn College (IL)"
    "Blessing-Rieman College of Nursing (IL)"
    "Bloomfield College (NJ)"
    "Bloomsburg University of Pennsylvania (PA)"
    "Blue Mountain College (MS)"
    "Bluefield College (VA)"
    "Bluefield State College (WV)"
    "Bluffton University (OH)"
    "Boise State University (ID)"
    "Boricua College (NY)"
    "Boston Architectural College (MA)"
    "Boston College (MA)"
    "Boston Conservatory (MA)"
    "Boston University (MA)"
    "Bowdoin College (ME)"
    "Bowie State University (MD)"
    "Bowling Green State University (OH)"
    "Bradley University (IL)"
    "Brandeis University (MA)"
    "Brandman University (CA)"
    "Brazosport College (TX)"
    "Brenau University (GA)"
    "Brescia University (KY)"
    "Brevard College (NC)"
    "Brewton-Parker College (GA)"
    "Briar Cliff University (IA)"
    "Briarcliffe College (NY)"
    "Bridgewater College (VA)"
    "Bridgewater State University (MA)"
    "Brigham Young University - Hawaii (HI)"
    "Brigham Young University - Idaho (ID)"
    "Brigham Young University - Provo (UT)"
    "Brock University (None)"
    "Brown University (RI)"
    "Bryan College (TN)"
    "Bryant University (RI)"
    "Bryn Athyn College of the New Church (PA)"
    "Bryn Mawr College (PA)"
    "Bucknell University (PA)"
    "Buena Vista University (IA)"
    "Burlington College (VT)"
    "Butler University (IN)"
    "Cabarrus College of Health Sciences (NC)"
    "Cabrini College (PA)"
    "Cairn University (PA)"
    "Caldwell College (NJ)"
    "California Baptist University (CA)"
    "California College of the Arts (CA)"
    "California Institute of Integral Studies (CA)"
    "California Institute of Technology (CA)"
    "California Institute of the Arts (CA)"
    "California Lutheran University (CA)"
    "California Maritime Academy (CA)"
    "California Polytechnic State University - San Luis Obispo (CA)"
    "California State Polytechnic University - Pomona (CA)"
    "California State University - Bakersfield (CA)"
    "California State University - Channel Islands (CA)"
    "California State University - Chico (CA)"
    "California State University - Dominguez Hills (CA)"
    "California State University - East Bay (CA)"
    "California State University - Fresno (CA)"
    "California State University - Fullerton (CA)"
    "California State University - Long Beach (CA)"
    "California State University - Los Angeles (CA)"
    "California State University - Monterey Bay (CA)"
    "California State University - Northridge (CA)"
    "California State University - Sacramento (CA)"
    "California State University - San Bernardino (CA)"
    "California State University - San Marcos (CA)"
    "California State University - Stanislaus (CA)"
    "California University of Pennsylvania (PA)"
    "Calumet College of St. Joseph (IN)"
    "Calvary Bible College and Theological Seminary (MO)"
    "Calvin College (MI)"
    "Cambridge College (MA)"
    "Cameron University (OK)"
    "Campbell University (NC)"
    "Campbellsville University (KY)"
    "Canisius College (NY)"
    "Capella University (MN)"
    "Capital University (OH)"
    "Capitol College (MD)"
    "Cardinal Stritch University (WI)"
    "Caribbean University (PR)"
    "Carleton College (MN)"
    "Carleton University (None)"
    "Carlos Albizu University (PR)"
    "Carlow University (PA)"
    "Carnegie Mellon University (PA)"
    "Carroll College (MT)"
    "Carroll University (WI)"
    "Carson-Newman University (TN)"
    "Carthage College (WI)"
    "Case Western Reserve University (OH)"
    "Castleton State College (VT)"
    "Catawba College (NC)"
    "Cazenovia College (NY)"
    "Cedar Crest College (PA)"
    "Cedarville University (OH)"
    "Centenary College (NJ)"
    "Centenary College of Louisiana (LA)"
    "Central Baptist College (AR)"
    "Central Bible College (MO)"
    "Central Christian College (KS)"
    "Central College (IA)"
    "Central Connecticut State University (CT)"
    "Central Methodist University (MO)"
    "Central Michigan University (MI)"
    "Central Penn College (PA)"
    "Central State University (OH)"
    "Central Washington University (WA)"
    "Centre College (KY)"
    "Chadron State College (NE)"
    "Chamberlain College of Nursing (IL)"
    "Chaminade University of Honolulu (HI)"
    "Champlain College (VT)"
    "Chancellor University (OH)"
    "Chapman University (CA)"
    "Charles R. Drew University of Medicine and Science (CA)"
    "Charleston Southern University (SC)"
    "Charter Oak State College (CT)"
    "Chatham University (PA)"
    "Chestnut Hill College (PA)"
    "Cheyney University of Pennsylvania (PA)"
    "Chicago State University (IL)"
    "Chipola College (FL)"
    "Chowan University (NC)"
    "Christendom College (VA)"
    "Christian Brothers University (TN)"
    "Christopher Newport University (VA)"
    "Cincinnati Christian University (OH)"
    "Cincinnati College of Mortuary Science (OH)"
    "City University of Seattle (WA)"
    "Claflin University (SC)"
    "Claremont McKenna College (CA)"
    "Clarion University of Pennsylvania (PA)"
    "Clark Atlanta University (GA)"
    "Clark University (MA)"
    "Clarke University (IA)"
    "Clarkson College (NE)"
    "Clarkson University (NY)"
    "Clayton State University (GA)"
    "Clear Creek Baptist Bible College (KY)"
    "Clearwater Christian College (FL)"
    "Cleary University (MI)"
    "Clemson University (SC)"
    "Cleveland Chiropractic College (MO)"
    "Cleveland Institute of Art (OH)"
    "Cleveland Institute of Music (OH)"
    "Cleveland State University (OH)"
    "Coastal Carolina University (SC)"
    "Coe College (IA)"
    "Cogswell Polytechnical College (CA)"
    "Coker College (SC)"
    "Colby College (ME)"
    "Colby-Sawyer College (NH)"
    "Colgate University (NY)"
    "College at Brockport - SUNY (NY)"
    "College for Creative Studies (MI)"
    "College of Charleston (SC)"
    "College of Idaho (ID)"
    "College of Mount St. Joseph (OH)"
    "College of Mount St. Vincent (NY)"
    "College of New Jersey (NJ)"
    "College of New Rochelle (NY)"
    "College of Our Lady of the Elms (MA)"
    "College of Saints John Fisher & Thomas More (TX)"
    "College of Southern Nevada (NV)"
    "College of St. Benedict (MN)"
    "College of St. Elizabeth (NJ)"
    "College of St. Joseph (VT)"
    "College of St. Mary (NE)"
    "College of St. Rose (NY)"
    "College of St. Scholastica (MN)"
    "College of the Atlantic (ME)"
    "College of the Holy Cross (MA)"
    "College of the Ozarks (MO)"
    "College of William and Mary (VA)"
    "College of Wooster (OH)"
    "Colorado Christian University (CO)"
    "Colorado College (CO)"
    "Colorado Mesa University (CO)"
    "Colorado School of Mines (CO)"
    "Colorado State University (CO)"
    "Colorado State University - Pueblo (CO)"
    "Colorado Technical University (CO)"
    "Columbia College (MO)"
    "Columbia College (SC)"
    "Columbia College Chicago (IL)"
    "Columbia College of Nursing (WI)"
    "Columbia International University (SC)"
    "Columbia University (NY)"
    "Columbus College of Art and Design (OH)"
    "Columbus State University (GA)"
    "Conception Seminary College (MO)"
    "Concord University (WV)"
    "Concordia College (AL)"
    "Concordia College (NY)"
    "Concordia College - Moorhead (MN)"
    "Concordia University (MI)"
    "Concordia University (NE)"
    "Concordia University (CA)"
    "Concordia University (OR)"
    "Concordia University (None)"
    "Concordia University Chicago (IL)"
    "Concordia University Texas (TX)"
    "Concordia University Wisconsin (WI)"
    "Concordia University - St. Paul (MN)"
    "Connecticut College (CT)"
    "Converse College (SC)"
    "Cooper Union (NY)"
    "Coppin State University (MD)"
    "Corban University (OR)"
    "Corcoran College of Art and Design (DC)"
    "Cornell College (IA)"
    "Cornell University (NY)"
    "Cornerstone University (MI)"
    "Cornish College of the Arts (WA)"
    "Covenant College (GA)"
    "Cox College (MO)"
    "Creighton University (NE)"
    "Criswell College (TX)"
    "Crown College (MN)"
    "Culinary Institute of America (NY)"
    "Culver-Stockton College (MO)"
    "Cumberland University (TN)"
    "CUNY - Baruch College (NY)"
    "CUNY - Brooklyn College (NY)"
    "CUNY - City College (NY)"
    "CUNY - College of Staten Island (NY)"
    "CUNY - Hunter College (NY)"
    "CUNY - John Jay College of Criminal Justice (NY)"
    "CUNY - Lehman College (NY)"
    "CUNY - Medgar Evers College (NY)"
    "CUNY - New York City College of Technology (NY)"
    "CUNY - Queens College (NY)"
    "CUNY - York College (NY)"
    "Curry College (MA)"
    "Curtis Institute of Music (PA)"
    "D'Youville College (NY)"
    "Daemen College (NY)"
    "Dakota State University (SD)"
    "Dakota Wesleyan University (SD)"
    "Dalhousie University (None)"
    "Dallas Baptist University (TX)"
    "Dallas Christian College (TX)"
    "Dalton State College (GA)"
    "Daniel Webster College (NH)"
    "Dartmouth College (NH)"
    "Davenport University (MI)"
    "Davidson College (NC)"
    "Davis and Elkins College (WV)"
    "Davis College (NY)"
    "Daytona State College (FL)"
    "Dean College (MA)"
    "Defiance College (OH)"
    "Delaware State University (DE)"
    "Delaware Valley College (PA)"
    "Delta State University (MS)"
    "Denison University (OH)"
    "DePaul University (IL)"
    "DePauw University (IN)"
    "DEREE - The American College of Greece (None)"
    "DeSales University (PA)"
    "DeVry University (IL)"
    "Dickinson College (PA)"
    "Dickinson State University (ND)"
    "Dillard University (LA)"
    "Divine Word College (IA)"
    "Dixie State College of Utah (UT)"
    "Doane College (NE)"
    "Dominican College (NY)"
    "Dominican University (IL)"
    "Dominican University of California (CA)"
    "Donnelly College (KS)"
    "Dordt College (IA)"
    "Dowling College (NY)"
    "Drake University (IA)"
    "Drew University (NJ)"
    "Drexel University (PA)"
    "Drury University (MO)"
    "Duke University (NC)"
    "Dunwoody College of Technology (MN)"
    "Duquesne University (PA)"
    "Earlham College (IN)"
    "East Carolina University (NC)"
    "East Central University (OK)"
    "East Stroudsburg University of Pennsylvania (PA)"
    "East Tennessee State University (TN)"
    "East Texas Baptist University (TX)"
    "East-West University (IL)"
    "Eastern Connecticut State University (CT)"
    "Eastern Illinois University (IL)"
    "Eastern Kentucky University (KY)"
    "Eastern Mennonite University (VA)"
    "Eastern Michigan University (MI)"
    "Eastern Nazarene College (MA)"
    "Eastern New Mexico University (NM)"
    "Eastern Oregon University (OR)"
    "Eastern University (PA)"
    "Eastern Washington University (WA)"
    "Eckerd College (FL)"
    "ECPI University (VA)"
    "Edgewood College (WI)"
    "Edinboro University of Pennsylvania (PA)"
    "Edison State College (FL)"
    "Edward Waters College (FL)"
    "Elizabeth City State University (NC)"
    "Elizabethtown College (PA)"
    "Elmhurst College (IL)"
    "Elmira College (NY)"
    "Elon University (NC)"
    "Embry-Riddle Aeronautical University (FL)"
    "Embry-Riddle Aeronautical University - Prescott (AZ)"
    "Emerson College (MA)"
    "Emmanuel College (GA)"
    "Emmanuel College (MA)"
    "Emmaus Bible College (IA)"
    "Emory and Henry College (VA)"
    "Emory University (GA)"
    "Emporia State University (KS)"
    "Endicott College (MA)"
    "Erskine College (SC)"
    "Escuela de Artes Plasticas de Puerto Rico (PR)"
    "Eureka College (IL)"
    "Evangel University (MO)"
    "Everest College - Phoenix (AZ)"
    "Everglades University (FL)"
    "Evergreen State College (WA)"
    "Excelsior College (NY)"
    "Fairfield University (CT)"
    "Fairleigh Dickinson University (NJ)"
    "Fairmont State University (WV)"
    "Faith Baptist Bible College and Theological Seminary (IA)"
    "Farmingdale State College - SUNY (NY)"
    "Fashion Institute of Technology (NY)"
    "Faulkner University (AL)"
    "Fayetteville State University (NC)"
    "Felician College (NJ)"
    "Ferris State University (MI)"
    "Ferrum College (VA)"
    "Finlandia University (MI)"
    "Fisher College (MA)"
    "Fisk University (TN)"
    "Fitchburg State University (MA)"
    "Five Towns College (NY)"
    "Flagler College (FL)"
    "Florida A&M University (FL)"
    "Florida Atlantic University (FL)"
    "Florida Christian College (FL)"
    "Florida College (FL)"
    "Florida Gulf Coast University (FL)"
    "Florida Institute of Technology (FL)"
    "Florida International University (FL)"
    "Florida Memorial University (FL)"
    "Florida Southern College (FL)"
    "Florida State College - Jacksonville (FL)"
    "Florida State University (FL)"
    "Fontbonne University (MO)"
    "Fordham University (NY)"
    "Fort Hays State University (KS)"
    "Fort Lewis College (CO)"
    "Fort Valley State University (GA)"
    "Framingham State University (MA)"
    "Francis Marion University (SC)"
    "Franciscan University of Steubenville (OH)"
    "Frank Lloyd Wright School of Architecture (AZ)"
    "Franklin and Marshall College (PA)"
    "Franklin College (IN)"
    "Franklin College Switzerland (None)"
    "Franklin Pierce University (NH)"
    "Franklin University (OH)"
    "Franklin W. Olin College of Engineering (MA)"
    "Freed-Hardeman University (TN)"
    "Fresno Pacific University (CA)"
    "Friends University (KS)"
    "Frostburg State University (MD)"
    "Furman University (SC)"
    "Gallaudet University (DC)"
    "Gannon University (PA)"
    "Gardner-Webb University (NC)"
    "Geneva College (PA)"
    "George Fox University (OR)"
    "George Mason University (VA)"
    "George Washington University (DC)"
    "Georgetown College (KY)"
    "Georgetown University (DC)"
    "Georgia College & State University (GA)"
    "Georgia Gwinnett College (GA)"
    "Georgia Institute of Technology (GA)"
    "Georgia Regents University (GA)"
    "Georgia Southern University (GA)"
    "Georgia Southwestern State University (GA)"
    "Georgia State University (GA)"
    "Georgian Court University (NJ)"
    "Gettysburg College (PA)"
    "Glenville State College (WV)"
    "God's Bible School and College (OH)"
    "Goddard College (VT)"
    "Golden Gate University (CA)"
    "Goldey-Beacom College (DE)"
    "Goldfarb School of Nursing at Barnes-Jewish College (MO)"
    "Gonzaga University (WA)"
    "Gordon College (MA)"
    "Gordon State College (GA)"
    "Goshen College (IN)"
    "Goucher College (MD)"
    "Governors State University (IL)"
    "Grace Bible College (MI)"
    "Grace College and Seminary (IN)"
    "Grace University (NE)"
    "Graceland University (IA)"
    "Grambling State University (LA)"
    "Grand Canyon University (AZ)"
    "Grand Valley State University (MI)"
    "Grand View University (IA)"
    "Granite State College (NH)"
    "Gratz College (PA)"
    "Great Basin College (NV)"
    "Great Lakes Christian College (MI)"
    "Green Mountain College (VT)"
    "Greensboro College (NC)"
    "Greenville College (IL)"
    "Grinnell College (IA)"
    "Grove City College (PA)"
    "Guilford College (NC)"
    "Gustavus Adolphus College (MN)"
    "Gwynedd-Mercy College (PA)"
    "Hamilton College (NY)"
    "Hamline University (MN)"
    "Hampden-Sydney College (VA)"
    "Hampshire College (MA)"
    "Hampton University (VA)"
    "Hannibal-LaGrange University (MO)"
    "Hanover College (IN)"
    "Hardin-Simmons University (TX)"
    "Harding University (AR)"
    "Harrington College of Design (IL)"
    "Harris-Stowe State University (MO)"
    "Harrisburg University of Science and Technology (PA)"
    "Hartwick College (NY)"
    "Harvard University (MA)"
    "Harvey Mudd College (CA)"
    "Haskell Indian Nations University (KS)"
    "Hastings College (NE)"
    "Haverford College (PA)"
    "Hawaii Pacific University (HI)"
    "Hebrew Theological College (IL)"
    "Heidelberg University (OH)"
    "Hellenic College (MA)"
    "Henderson State University (AR)"
    "Hendrix College (AR)"
    "Heritage University (WA)"
    "Herzing University (WI)"
    "Hesser College (NH)"
    "High Point University (NC)"
    "Hilbert College (NY)"
    "Hillsdale College (MI)"
    "Hiram College (OH)"
    "Hobart and William Smith Colleges (NY)"
    "Hodges University (FL)"
    "Hofstra University (NY)"
    "Hollins University (VA)"
    "Holy Apostles College and Seminary (CT)"
    "Holy Cross College (IN)"
    "Holy Family University (PA)"
    "Holy Names University (CA)"
    "Hood College (MD)"
    "Hope College (MI)"
    "Hope International University (CA)"
    "Houghton College (NY)"
    "Houston Baptist University (TX)"
    "Howard Payne University (TX)"
    "Howard University (DC)"
    "Hult International Business School (None)"
    "Humboldt State University (CA)"
    "Humphreys College (CA)"
    "Huntingdon College (AL)"
    "Huntington University (IN)"
    "Husson University (ME)"
    "Huston-Tillotson University (TX)"
    "Idaho State University (ID)"
    "Illinois College (IL)"
    "Illinois Institute of Art at Chicago (IL)"
    "Illinois Institute of Technology (IL)"
    "Illinois State University (IL)"
    "Illinois Wesleyan University (IL)"
    "Immaculata University (PA)"
    "Indian River State College (FL)"
    "Indiana Institute of Technology (IN)"
    "Indiana State University (IN)"
    "Indiana University East (IN)"
    "Indiana University Northwest (IN)"
    "Indiana University of Pennsylvania (PA)"
    "Indiana University Southeast (IN)"
    "Indiana University - Bloomington (IN)"
    "Indiana University - Kokomo (IN)"
    "Indiana University - South Bend (IN)"
    "Indiana University-Purdue University - Fort Wayne (IN)"
    "Indiana University-Purdue University - Indianapolis (IN)"
    "Indiana Wesleyan University (IN)"
    "Institute of American Indian and Alaska Native Culture and Arts Development (NM)"
    "Inter American University of Puerto Rico - Aguadilla (PR)"
    "Inter American University of Puerto Rico - Arecibo (PR)"
    "Inter American University of Puerto Rico - Barranquitas (PR)"
    "Inter American University of Puerto Rico - Bayamon (PR)"
    "Inter American University of Puerto Rico - Fajardo (PR)"
    "Inter American University of Puerto Rico - Guayama (PR)"
    "Inter American University of Puerto Rico - Metropolitan Campus (PR)"
    "Inter American University of Puerto Rico - Ponce (PR)"
    "Inter American University of Puerto Rico - San German (PR)"
    "International College of the Cayman Islands (None)"
    "Iona College (NY)"
    "Iowa State University (IA)"
    "Iowa Wesleyan College (IA)"
    "Ithaca College (NY)"
    "Jackson State University (MS)"
    "Jacksonville State University (AL)"
    "Jacksonville University (FL)"
    "James Madison University (VA)"
    "Jarvis Christian College (TX)"
    "Jewish Theological Seminary of America (NY)"
    "John Brown University (AR)"
    "John Carroll University (OH)"
    "John F. Kennedy University (CA)"
    "Johns Hopkins University (MD)"
    "Johnson & Wales University (RI)"
    "Johnson C. Smith University (NC)"
    "Johnson State College (VT)"
    "Johnson University (TN)"
    "Jones International University (CO)"
    "Judson College (AL)"
    "Judson University (IL)"
    "Juilliard School (NY)"
    "Juniata College (PA)"
    "Kalamazoo College (MI)"
    "Kansas City Art Institute (MO)"
    "Kansas State University (KS)"
    "Kansas Wesleyan University (KS)"
    "Kaplan University (IA)"
    "Kean University (NJ)"
    "Keene State College (NH)"
    "Keiser University (FL)"
    "Kendall College (IL)"
    "Kennesaw State University (GA)"
    "Kent State University (OH)"
    "Kentucky Christian University (KY)"
    "Kentucky State University (KY)"
    "Kentucky Wesleyan College (KY)"
    "Kenyon College (OH)"
    "Kettering College (OH)"
    "Kettering University (MI)"
    "Keuka College (NY)"
    "Keystone College (PA)"
    "King University (TN)"
    "King's College (PA)"
    "King's College (NY)"
    "Knox College (IL)"
    "Kutztown University of Pennsylvania (PA)"
    "Kuyper College (MI)"
    "La Roche College (PA)"
    "La Salle University (PA)"
    "La Sierra University (CA)"
    "Lafayette College (PA)"
    "LaGrange College (GA)"
    "Laguna College of Art and Design (CA)"
    "Lake Erie College (OH)"
    "Lake Forest College (IL)"
    "Lake Superior State University (MI)"
    "Lakeland College (WI)"
    "Lakeview College of Nursing (IL)"
    "Lamar University (TX)"
    "Lancaster Bible College (PA)"
    "Lander University (SC)"
    "Lane College (TN)"
    "Langston University (OK)"
    "Lasell College (MA)"
    "Lawrence Technological University (MI)"
    "Lawrence University (WI)"
    "Le Moyne College (NY)"
    "Lebanon Valley College (PA)"
    "Lee University (TN)"
    "Lees-McRae College (NC)"
    "Lehigh University (PA)"
    "LeMoyne-Owen College (TN)"
    "Lenoir-Rhyne University (NC)"
    "Lesley University (MA)"
    "LeTourneau University (TX)"
    "Lewis & Clark College (OR)"
    "Lewis University (IL)"
    "Lewis-Clark State College (ID)"
    "Lexington College (IL)"
    "Liberty University (VA)"
    "Life Pacific College (CA)"
    "Life University (GA)"
    "LIM College (NY)"
    "Limestone College (SC)"
    "Lincoln Christian University (IL)"
    "Lincoln College (IL)"
    "Lincoln Memorial University (TN)"
    "Lincoln University (MO)"
    "Lincoln University (PA)"
    "Lindenwood University (MO)"
    "Lindsey Wilson College (KY)"
    "Linfield College (OR)"
    "Lipscomb University (TN)"
    "LIU Post (NY)"
    "Livingstone College (NC)"
    "Lock Haven University of Pennsylvania (PA)"
    "Loma Linda University (CA)"
    "Longwood University (VA)"
    "Loras College (IA)"
    "Louisiana College (LA)"
    "Louisiana State University Health Sciences Center (LA)"
    "Louisiana State University - Alexandria (LA)"
    "Louisiana State University - Baton Rouge (LA)"
    "Louisiana State University - Shreveport (LA)"
    "Louisiana Tech University (LA)"
    "Lourdes University (OH)"
    "Loyola Marymount University (CA)"
    "Loyola University Chicago (IL)"
    "Loyola University Maryland (MD)"
    "Loyola University New Orleans (LA)"
    "Lubbock Christian University (TX)"
    "Luther College (IA)"
    "Lycoming College (PA)"
    "Lyme Academy College of Fine Arts (CT)"
    "Lynchburg College (VA)"
    "Lyndon State College (VT)"
    "Lynn University (FL)"
    "Lyon College (AR)"
    "Macalester College (MN)"
    "MacMurray College (IL)"
    "Madonna University (MI)"
    "Maharishi University of Management (IA)"
    "Maine College of Art (ME)"
    "Maine Maritime Academy (ME)"
    "Malone University (OH)"
    "Manchester University (IN)"
    "Manhattan Christian College (KS)"
    "Manhattan College (NY)"
    "Manhattan School of Music (NY)"
    "Manhattanville College (NY)"
    "Mansfield University of Pennsylvania (PA)"
    "Maranatha Baptist Bible College (WI)"
    "Marian University (IN)"
    "Marian University (WI)"
    "Marietta College (OH)"
    "Marist College (NY)"
    "Marlboro College (VT)"
    "Marquette University (WI)"
    "Mars Hill University (NC)"
    "Marshall University (WV)"
    "Martin Luther College (MN)"
    "Martin Methodist College (TN)"
    "Martin University (IN)"
    "Mary Baldwin College (VA)"
    "Marygrove College (MI)"
    "Maryland Institute College of Art (MD)"
    "Marylhurst University (OR)"
    "Marymount Manhattan College (NY)"
    "Marymount University (VA)"
    "Maryville College (TN)"
    "Maryville University of St. Louis (MO)"
    "Marywood University (PA)"
    "Massachusetts College of Art and Design (MA)"
    "Massachusetts College of Liberal Arts (MA)"
    "Massachusetts College of Pharmacy and Health Sciences (MA)"
    "Massachusetts Institute of Technology (MA)"
    "Massachusetts Maritime Academy (MA)"
    "Master's College and Seminary (CA)"
    "Mayville State University (ND)"
    "McDaniel College (MD)"
    "McGill University (None)"
    "McKendree University (IL)"
    "McMurry University (TX)"
    "McNeese State University (LA)"
    "McPherson College (KS)"
    "Medaille College (NY)"
    "Medical University of South Carolina (SC)"
    "Memorial University of Newfoundland (None)"
    "Memphis College of Art (TN)"
    "Menlo College (CA)"
    "Mercer University (GA)"
    "Mercy College (NY)"
    "Mercy College of Health Sciences (IA)"
    "Mercy College of Ohio (OH)"
    "Mercyhurst University (PA)"
    "Meredith College (NC)"
    "Merrimack College (MA)"
    "Messiah College (PA)"
    "Methodist University (NC)"
    "Metropolitan College of New York (NY)"
    "Metropolitan State University (MN)"
    "Metropolitan State University of Denver (CO)"
    "Miami Dade College (FL)"
    "Miami International University of Art & Design (FL)"
    "Miami University - Oxford (OH)"
    "Michigan State University (MI)"
    "Michigan Technological University (MI)"
    "Mid-America Christian University (OK)"
    "Mid-Atlantic Christian University (NC)"
    "Mid-Continent University (KY)"
    "MidAmerica Nazarene University (KS)"
    "Middle Georgia State College (GA)"
    "Middle Tennessee State University (TN)"
    "Middlebury College (VT)"
    "Midland College (TX)"
    "Midland University (NE)"
    "Midstate College (IL)"
    "Midway College (KY)"
    "Midwestern State University (TX)"
    "Miles College (AL)"
    "Millersville University of Pennsylvania (PA)"
    "Milligan College (TN)"
    "Millikin University (IL)"
    "Mills College (CA)"
    "Millsaps College (MS)"
    "Milwaukee Institute of Art and Design (WI)"
    "Milwaukee School of Engineering (WI)"
    "Minneapolis College of Art and Design (MN)"
    "Minnesota State University - Mankato (MN)"
    "Minnesota State University - Moorhead (MN)"
    "Minot State University (ND)"
    "Misericordia University (PA)"
    "Mississippi College (MS)"
    "Mississippi State University (MS)"
    "Mississippi University for Women (MS)"
    "Mississippi Valley State University (MS)"
    "Missouri Baptist University (MO)"
    "Missouri Southern State University (MO)"
    "Missouri State University (MO)"
    "Missouri University of Science & Technology (MO)"
    "Missouri Valley College (MO)"
    "Missouri Western State University (MO)"
    "Mitchell College (CT)"
    "Molloy College (NY)"
    "Monmouth College (IL)"
    "Monmouth University (NJ)"
    "Monroe College (NY)"
    "Montana State University (MT)"
    "Montana State University - Billings (MT)"
    "Montana State University - Northern (MT)"
    "Montana Tech of the University of Montana (MT)"
    "Montclair State University (NJ)"
    "Monterrey Institute of Technology and Higher Education - Monterrey (None)"
    "Montreat College (NC)"
    "Montserrat College of Art (MA)"
    "Moody Bible Institute (IL)"
    "Moore College of Art & Design (PA)"
    "Moravian College (PA)"
    "Morehead State University (KY)"
    "Morehouse College (GA)"
    "Morgan State University (MD)"
    "Morningside College (IA)"
    "Morris College (SC)"
    "Morrisville State College (NY)"
    "Mount Aloysius College (PA)"
    "Mount Angel Seminary (OR)"
    "Mount Carmel College of Nursing (OH)"
    "Mount Holyoke College (MA)"
    "Mount Ida College (MA)"
    "Mount Marty College (SD)"
    "Mount Mary University (WI)"
    "Mount Mercy University (IA)"
    "Mount Olive College (NC)"
    "Mount St. Mary College (NY)"
    "Mount St. Mary's College (CA)"
    "Mount St. Mary's University (MD)"
    "Mount Vernon Nazarene University (OH)"
    "Muhlenberg College (PA)"
    "Multnomah University (OR)"
    "Murray State University (KY)"
    "Muskingum University (OH)"
    "Naropa University (CO)"
    "National American University (SD)"
    "National Graduate School of Quality Management (MA)"
    "National Hispanic University (CA)"
    "National Labor College (MD)"
    "National University (CA)"
    "National-Louis University (IL)"
    "Nazarene Bible College (CO)"
    "Nazareth College (NY)"
    "Nebraska Methodist College (NE)"
    "Nebraska Wesleyan University (NE)"
    "Neumann University (PA)"
    "Nevada State College (NV)"
    "New College of Florida (FL)"
    "New England College (NH)"
    "New England Conservatory of Music (MA)"
    "New England Institute of Art (MA)"
    "New England Institute of Technology (RI)"
    "New Jersey City University (NJ)"
    "New Jersey Institute of Technology (NJ)"
    "New Mexico Highlands University (NM)"
    "New Mexico Institute of Mining and Technology (NM)"
    "New Mexico State University (NM)"
    "New Orleans Baptist Theological Seminary (LA)"
    "New School (NY)"
    "New York Institute of Technology (NY)"
    "New York University (NY)"
    "Newberry College (SC)"
    "Newbury College (MA)"
    "Newman University (KS)"
    "Niagara University (NY)"
    "Nicholls State University (LA)"
    "Nichols College (MA)"
    "Norfolk State University (VA)"
    "North Carolina A&T State University (NC)"
    "North Carolina Central University (NC)"
    "North Carolina State University - Raleigh (NC)"
    "North Carolina Wesleyan College (NC)"
    "North Central College (IL)"
    "North Central University (MN)"
    "North Dakota State University (ND)"
    "North Greenville University (SC)"
    "North Park University (IL)"
    "Northcentral University (AZ)"
    "Northeastern Illinois University (IL)"
    "Northeastern State University (OK)"
    "Northeastern University (MA)"
    "Northern Arizona University (AZ)"
    "Northern Illinois University (IL)"
    "Northern Kentucky University (KY)"
    "Northern Michigan University (MI)"
    "Northern New Mexico College (NM)"
    "Northern State University (SD)"
    "Northland College (WI)"
    "Northwest Christian University (OR)"
    "Northwest Florida State College (FL)"
    "Northwest Missouri State University (MO)"
    "Northwest Nazarene University (ID)"
    "Northwest University (WA)"
    "Northwestern College (IA)"
    "Northwestern Health Sciences University (MN)"
    "Northwestern Oklahoma State University (OK)"
    "Northwestern State University of Louisiana (LA)"
    "Northwestern University (IL)"
    "Northwood University (MI)"
    "Norwich University (VT)"
    "Notre Dame College of Ohio (OH)"
    "Notre Dame de Namur University (CA)"
    "Notre Dame of Maryland University (MD)"
    "Nova Scotia College of Art and Design (None)"
    "Nova Southeastern University (FL)"
    "Nyack College (NY)"
    "Oakland City University (IN)"
    "Oakland University (MI)"
    "Oakwood University (AL)"
    "Oberlin College (OH)"
    "Occidental College (CA)"
    "Oglala Lakota College (SD)"
    "Oglethorpe University (GA)"
    "Ohio Christian University (OH)"
    "Ohio Dominican University (OH)"
    "Ohio Northern University (OH)"
    "Ohio State University - Columbus (OH)"
    "Ohio University (OH)"
    "Ohio Valley University (WV)"
    "Ohio Wesleyan University (OH)"
    "Oklahoma Baptist University (OK)"
    "Oklahoma Christian University (OK)"
    "Oklahoma City University (OK)"
    "Oklahoma Panhandle State University (OK)"
    "Oklahoma State University (OK)"
    "Oklahoma State University Institute of Technology - Okmulgee (OK)"
    "Oklahoma State University - Oklahoma City (OK)"
    "Oklahoma Wesleyan University (OK)"
    "Old Dominion University (VA)"
    "Olivet College (MI)"
    "Olivet Nazarene University (IL)"
    "Olympic College (WA)"
    "Oral Roberts University (OK)"
    "Oregon College of Art and Craft (OR)"
    "Oregon Health and Science University (OR)"
    "Oregon Institute of Technology (OR)"
    "Oregon State University (OR)"
    "Otis College of Art and Design (CA)"
    "Ottawa University (KS)"
    "Otterbein University (OH)"
    "Ouachita Baptist University (AR)"
    "Our Lady of Holy Cross College (LA)"
    "Our Lady of the Lake College (LA)"
    "Our Lady of the Lake University (TX)"
    "Pace University (NY)"
    "Pacific Lutheran University (WA)"
    "Pacific Northwest College of Art (OR)"
    "Pacific Oaks College (CA)"
    "Pacific Union College (CA)"
    "Pacific University (OR)"
    "Paine College (GA)"
    "Palm Beach Atlantic University (FL)"
    "Palmer College of Chiropractic (IA)"
    "Park University (MO)"
    "Parker University (TX)"
    "Patten University (CA)"
    "Paul Smith's College (NY)"
    "Peirce College (PA)"
    "Peninsula College (WA)"
    "Pennsylvania College of Art and Design (PA)"
    "Pennsylvania College of Technology (PA)"
    "Pennsylvania State University - Erie, The Behrend College (PA)"
    "Pennsylvania State University - Harrisburg (PA)"
    "Pennsylvania State University - University Park (PA)"
    "Pepperdine University (CA)"
    "Peru State College (NE)"
    "Pfeiffer University (NC)"
    "Philadelphia University (PA)"
    "Philander Smith College (AR)"
    "Piedmont College (GA)"
    "Pine Manor College (MA)"
    "Pittsburg State University (KS)"
    "Pitzer College (CA)"
    "Plaza College (NY)"
    "Plymouth State University (NH)"
    "Point Loma Nazarene University (CA)"
    "Point Park University (PA)"
    "Point University (GA)"
    "Polytechnic Institute of New York University (NY)"
    "Pomona College (CA)"
    "Pontifical Catholic University of Puerto Rico (PR)"
    "Pontifical College Josephinum (OH)"
    "Portland State University (OR)"
    "Post University (CT)"
    "Potomac College (DC)"
    "Prairie View A&M University (TX)"
    "Pratt Institute (NY)"
    "Presbyterian College (SC)"
    "Prescott College (AZ)"
    "Presentation College (SD)"
    "Princeton University (NJ)"
    "Principia College (IL)"
    "Providence College (RI)"
    "Puerto Rico Conservatory of Music (PR)"
    "Purchase College - SUNY (NY)"
    "Purdue University - Calumet (IN)"
    "Purdue University - North Central (IN)"
    "Purdue University - West Lafayette (IN)"
    "Queens University of Charlotte (NC)"
    "Quincy University (IL)"
    "Quinnipiac University (CT)"
    "Radford University (VA)"
    "Ramapo College of New Jersey (NJ)"
    "Randolph College (VA)"
    "Randolph-Macon College (VA)"
    "Ranken Technical College (MO)"
    "Reed College (OR)"
    "Regent University (VA)"
    "Regent's American College London (None)"
    "Regis College (MA)"
    "Regis University (CO)"
    "Reinhardt University (GA)"
    "Rensselaer Polytechnic Institute (NY)"
    "Research College of Nursing (MO)"
    "Resurrection University (IL)"
    "Rhode Island College (RI)"
    "Rhode Island School of Design (RI)"
    "Rhodes College (TN)"
    "Rice University (TX)"
    "Richard Stockton College of New Jersey (NJ)"
    "Richmond - The American International University in London (None)"
    "Rider University (NJ)"
    "Ringling College of Art and Design (FL)"
    "Ripon College (WI)"
    "Rivier University (NH)"
    "Roanoke College (VA)"
    "Robert B. Miller College (MI)"
    "Robert Morris University (IL)"
    "Robert Morris University (PA)"
    "Roberts Wesleyan College (NY)"
    "Rochester College (MI)"
    "Rochester Institute of Technology (NY)"
    "Rockford University (IL)"
    "Rockhurst University (MO)"
    "Rocky Mountain College (MT)"
    "Rocky Mountain College of Art and Design (CO)"
    "Roger Williams University (RI)"
    "Rogers State University (OK)"
    "Rollins College (FL)"
    "Roosevelt University (IL)"
    "Rosalind Franklin University of Medicine and Science (IL)"
    "Rose-Hulman Institute of Technology (IN)"
    "Rosemont College (PA)"
    "Rowan University (NJ)"
    "Rush University (IL)"
    "Rust College (MS)"
    "Rutgers, the State University of New Jersey - Camden (NJ)"
    "Rutgers, the State University of New Jersey - New Brunswick (NJ)"
    "Rutgers, the State University of New Jersey - Newark (NJ)"
    "Ryerson University (None)"
    "Sacred Heart Major Seminary (MI)"
    "Sacred Heart University (CT)"
    "Saginaw Valley State University (MI)"
    "Salem College (NC)"
    "Salem International University (WV)"
    "Salem State University (MA)"
    "Salisbury University (MD)"
    "Salish Kootenai College (MT)"
    "Salve Regina University (RI)"
    "Sam Houston State University (TX)"
    "Samford University (AL)"
    "Samuel Merritt University (CA)"
    "San Diego Christian College (CA)"
    "San Diego State University (CA)"
    "San Francisco Art Institute (CA)"
    "San Francisco Conservatory of Music (CA)"
    "San Francisco State University (CA)"
    "San Jose State University (CA)"
    "Sanford College of Nursing (ND)"
    "Santa Clara University (CA)"
    "Santa Fe University of Art and Design (NM)"
    "Sarah Lawrence College (NY)"
    "Savannah College of Art and Design (GA)"
    "Savannah State University (GA)"
    "School of the Art Institute of Chicago (IL)"
    "School of Visual Arts (NY)"
    "Schreiner University (TX)"
    "Scripps College (CA)"
    "Seattle Pacific University (WA)"
    "Seattle University (WA)"
    "Seton Hall University (NJ)"
    "Seton Hill University (PA)"
    "Sewanee - University of the South (TN)"
    "Shaw University (NC)"
    "Shawnee State University (OH)"
    "Shenandoah University (VA)"
    "Shepherd University (WV)"
    "Shimer College (IL)"
    "Shippensburg University of Pennsylvania (PA)"
    "Shorter University (GA)"
    "Siena College (NY)"
    "Siena Heights University (MI)"
    "Sierra Nevada College (NV)"
    "Silver Lake College (WI)"
    "Simmons College (MA)"
    "Simon Fraser University (None)"
    "Simpson College (IA)"
    "Simpson University (CA)"
    "Sinte Gleska University (SD)"
    "Sitting Bull College (ND)"
    "Skidmore College (NY)"
    "Slippery Rock University of Pennsylvania (PA)"
    "Smith College (MA)"
    "Sojourner-Douglass College (MD)"
    "Soka University of America (CA)"
    "Sonoma State University (CA)"
    "South Carolina State University (SC)"
    "South College (TN)"
    "South Dakota School of Mines and Technology (SD)"
    "South Dakota State University (SD)"
    "South Seattle Community College (WA)"
    "South Texas College (TX)"
    "South University (GA)"
    "Southeast Missouri State University (MO)"
    "Southeastern Louisiana University (LA)"
    "Southeastern Oklahoma State University (OK)"
    "Southeastern University (FL)"
    "Southern Adventist University (TN)"
    "Southern Arkansas University (AR)"
    "Southern Baptist Theological Seminary (KY)"
    "Southern California Institute of Architecture (CA)"
    "Southern Connecticut State University (CT)"
    "Southern Illinois University - Carbondale (IL)"
    "Southern Illinois University - Edwardsville (IL)"
    "Southern Methodist University (TX)"
    "Southern Nazarene University (OK)"
    "Southern New Hampshire University (NH)"
    "Southern Oregon University (OR)"
    "Southern Polytechnic State University (GA)"
    "Southern University and A&M College (LA)"
    "Southern University - New Orleans (LA)"
    "Southern Utah University (UT)"
    "Southern Vermont College (VT)"
    "Southern Wesleyan University (SC)"
    "Southwest Baptist University (MO)"
    "Southwest Minnesota State University (MN)"
    "Southwest University of Visual Arts (AZ)"
    "Southwestern Adventist University (TX)"
    "Southwestern Assemblies of God University (TX)"
    "Southwestern Christian College (TX)"
    "Southwestern Christian University (OK)"
    "Southwestern College (KS)"
    "Southwestern Oklahoma State University (OK)"
    "Southwestern University (TX)"
    "Spalding University (KY)"
    "Spelman College (GA)"
    "Spring Arbor University (MI)"
    "Spring Hill College (AL)"
    "Springfield College (MA)"
    "St. Ambrose University (IA)"
    "St. Anselm College (NH)"
    "St. Anthony College of Nursing (IL)"
    "St. Augustine College (IL)"
    "St. Augustine's University (NC)"
    "St. Bonaventure University (NY)"
    "St. Catharine College (KY)"
    "St. Catherine University (MN)"
    "St. Charles Borromeo Seminary (PA)"
    "St. Cloud State University (MN)"
    "St. Edward's University (TX)"
    "St. Francis College (NY)"
    "St. Francis Medical Center College of Nursing (IL)"
    "St. Francis University (PA)"
    "St. Gregory's University (OK)"
    "St. John Fisher College (NY)"
    "St. John Vianney College Seminary (FL)"
    "St. John's College (MD)"
    "St. John's College (NM)"
    "St. John's College (IL)"
    "St. John's University (MN)"
    "St. John's University (NY)"
    "St. Joseph Seminary College (LA)"
    "St. Joseph's College (IN)"
    "St. Joseph's College (ME)"
    "St. Joseph's College New York (NY)"
    "St. Joseph's University (PA)"
    "St. Lawrence University (NY)"
    "St. Leo University (FL)"
    "St. Louis College of Pharmacy (MO)"
    "St. Louis University (MO)"
    "St. Luke's College of Health Sciences (MO)"
    "St. Martin's University (WA)"
    "St. Mary's College (IN)"
    "St. Mary's College of California (CA)"
    "St. Mary's College of Maryland (MD)"
    "St. Mary's Seminary and University (MD)"
    "St. Mary's University of Minnesota (MN)"
    "St. Mary's University of San Antonio (TX)"
    "St. Mary-of-the-Woods College (IN)"
    "St. Michael's College (VT)"
    "St. Norbert College (WI)"
    "St. Olaf College (MN)"
    "St. Paul's College (VA)"
    "St. Peter's University (NJ)"
    "St. Petersburg College (FL)"
    "St. Thomas Aquinas College (NY)"
    "St. Thomas University (FL)"
    "St. Vincent College (PA)"
    "St. Xavier University (IL)"
    "Stanford University (CA)"
    "Stephen F. Austin State University (TX)"
    "Stephens College (MO)"
    "Sterling College (KS)"
    "Sterling College (VT)"
    "Stetson University (FL)"
    "Stevens Institute of Technology (NJ)"
    "Stevenson University (MD)"
    "Stillman College (AL)"
    "Stonehill College (MA)"
    "Stony Brook University - SUNY (NY)"
    "Strayer University (DC)"
    "Suffolk University (MA)"
    "Sul Ross State University (TX)"
    "Sullivan University (KY)"
    "SUNY Buffalo State (NY)"
    "SUNY College of Agriculture and Technology - Cobleskill (NY)"
    "SUNY College of Environmental Science and Forestry (NY)"
    "SUNY College of Technology - Alfred (NY)"
    "SUNY College of Technology - Canton (NY)"
    "SUNY College of Technology - Delhi (NY)"
    "SUNY College - Cortland (NY)"
    "SUNY College - Old Westbury (NY)"
    "SUNY College - Oneonta (NY)"
    "SUNY College - Potsdam (NY)"
    "SUNY Downstate Medical Center (NY)"
    "SUNY Empire State College (NY)"
    "SUNY Institute of Technology - Utica/Rome (NY)"
    "SUNY Maritime College (NY)"
    "SUNY Upstate Medical University (NY)"
    "SUNY - Fredonia (NY)"
    "SUNY - Geneseo (NY)"
    "SUNY - New Paltz (NY)"
    "SUNY - Oswego (NY)"
    "SUNY - Plattsburgh (NY)"
    "Susquehanna University (PA)"
    "Swarthmore College (PA)"
    "Sweet Briar College (VA)"
    "Syracuse University (NY)"
    "Tabor College (KS)"
    "Talladega College (AL)"
    "Tarleton State University (TX)"
    "Taylor University (IN)"
    "Temple University (PA)"
    "Tennessee State University (TN)"
    "Tennessee Technological University (TN)"
    "Tennessee Wesleyan College (TN)"
    "Texas A&M International University (TX)"
    "Texas A&M University - College Station (TX)"
    "Texas A&M University - Commerce (TX)"
    "Texas A&M University - Corpus Christi (TX)"
    "Texas A&M University - Galveston (TX)"
    "Texas A&M University - Kingsville (TX)"
    "Texas A&M University - Texarkana (TX)"
    "Texas Christian University (TX)"
    "Texas College (TX)"
    "Texas Lutheran University (TX)"
    "Texas Southern University (TX)"
    "Texas State University (TX)"
    "Texas Tech University (TX)"
    "Texas Tech University Health Sciences Center (TX)"
    "Texas Wesleyan University (TX)"
    "Texas Woman's University (TX)"
    "The Catholic University of America (DC)"
    "The Citadel (SC)"
    "The Sage Colleges (NY)"
    "Thiel College (PA)"
    "Thomas Aquinas College (CA)"
    "Thomas College (ME)"
    "Thomas Edison State College (NJ)"
    "Thomas Jefferson University (PA)"
    "Thomas More College (KY)"
    "Thomas More College of Liberal Arts (NH)"
    "Thomas University (GA)"
    "Tiffin University (OH)"
    "Tilburg University (None)"
    "Toccoa Falls College (GA)"
    "Tougaloo College (MS)"
    "Touro College (NY)"
    "Towson University (MD)"
    "Transylvania University (KY)"
    "Trent University (None)"
    "Trevecca Nazarene University (TN)"
    "Trident University International (CA)"
    "Trine University (IN)"
    "Trinity Christian College (IL)"
    "Trinity College (CT)"
    "Trinity College of Nursing & Health Sciences (IL)"
    "Trinity International University (IL)"
    "Trinity Lutheran College (WA)"
    "Trinity University (DC)"
    "Trinity University (TX)"
    "Trinity Western University (None)"
    "Troy University (AL)"
    "Truett McConnell College (GA)"
    "Truman State University (MO)"
    "Tufts University (MA)"
    "Tulane University (LA)"
    "Tusculum College (TN)"
    "Tuskegee University (AL)"
    "Union College (KY)"
    "Union College (NE)"
    "Union College (NY)"
    "Union Institute and University (OH)"
    "Union University (TN)"
    "United States Air Force Academy (CO)"
    "United States Coast Guard Academy (CT)"
    "United States International University - Kenya (None)"
    "United States Merchant Marine Academy (NY)"
    "United States Military Academy (NY)"
    "United States Naval Academy (MD)"
    "United States Sports Academy (AL)"
    "Unity College (ME)"
    "Universidad Adventista de las Antillas (PR)"
    "Universidad del Este (PR)"
    "Universidad del Turabo (PR)"
    "Universidad Metropolitana (PR)"
    "Universidad Politecnica De Puerto Rico (PR)"
    "University at Albany - SUNY (NY)"
    "University at Buffalo - SUNY (NY)"
    "University of Advancing Technology (AZ)"
    "University of Akron (OH)"
    "University of Alabama (AL)"
    "University of Alabama - Birmingham (AL)"
    "University of Alabama - Huntsville (AL)"
    "University of Alaska - Anchorage (AK)"
    "University of Alaska - Fairbanks (AK)"
    "University of Alaska - Southeast (AK)"
    "University of Alberta (None)"
    "University of Arizona (AZ)"
    "University of Arkansas (AR)"
    "University of Arkansas for Medical Sciences (AR)"
    "University of Arkansas - Fort Smith (AR)"
    "University of Arkansas - Little Rock (AR)"
    "University of Arkansas - Monticello (AR)"
    "University of Arkansas - Pine Bluff (AR)"
    "University of Baltimore (MD)"
    "University of Bridgeport (CT)"
    "University of British Columbia (None)"
    "University of Calgary (None)"
    "University of California - Berkeley (CA)"
    "University of California - Davis (CA)"
    "University of California - Irvine (CA)"
    "University of California - Los Angeles (CA)"
    "University of California - Riverside (CA)"
    "University of California - San Diego (CA)"
    "University of California - Santa Barbara (CA)"
    "University of California - Santa Cruz (CA)"
    "University of Central Arkansas (AR)"
    "University of Central Florida (FL)"
    "University of Central Missouri (MO)"
    "University of Central Oklahoma (OK)"
    "University of Charleston (WV)"
    "University of Chicago (IL)"
    "University of Cincinnati (OH)"
    "University of Cincinnati - UC Blue Ash College (OH)"
    "University of Colorado - Boulder (CO)"
    "University of Colorado - Colorado Springs (CO)"
    "University of Colorado - Denver (CO)"
    "University of Connecticut (CT)"
    "University of Dallas (TX)"
    "University of Dayton (OH)"
    "University of Delaware (DE)"
    "University of Denver (CO)"
    "University of Detroit Mercy (MI)"
    "University of Dubuque (IA)"
    "University of Evansville (IN)"
    "University of Findlay (OH)"
    "University of Florida (FL)"
    "University of Georgia (GA)"
    "University of Great Falls (MT)"
    "University of Guam (GU)"
    "University of Guelph (None)"
    "University of Hartford (CT)"
    "University of Hawaii - Hilo (HI)"
    "University of Hawaii - Manoa (HI)"
    "University of Hawaii - Maui College (HI)"
    "University of Hawaii - West Oahu (HI)"
    "University of Houston (TX)"
    "University of Houston - Clear Lake (TX)"
    "University of Houston - Downtown (TX)"
    "University of Houston - Victoria (TX)"
    "University of Idaho (ID)"
    "University of Illinois - Chicago (IL)"
    "University of Illinois - Springfield (IL)"
    "University of Illinois - Urbana-Champaign (IL)"
    "University of Indianapolis (IN)"
    "University of Iowa (IA)"
    "University of Jamestown (ND)"
    "University of Kansas (KS)"
    "University of Kentucky (KY)"
    "University of La Verne (CA)"
    "University of Louisiana - Lafayette (LA)"
    "University of Louisiana - Monroe (LA)"
    "University of Louisville (KY)"
    "University of Maine (ME)"
    "University of Maine - Augusta (ME)"
    "University of Maine - Farmington (ME)"
    "University of Maine - Fort Kent (ME)"
    "University of Maine - Machias (ME)"
    "University of Maine - Presque Isle (ME)"
    "University of Mary (ND)"
    "University of Mary Hardin-Baylor (TX)"
    "University of Mary Washington (VA)"
    "University of Maryland - Baltimore (MD)"
    "University of Maryland - Baltimore County (MD)"
    "University of Maryland - College Park (MD)"
    "University of Maryland - Eastern Shore (MD)"
    "University of Maryland - University College (MD)"
    "University of Massachusetts - Amherst (MA)"
    "University of Massachusetts - Boston (MA)"
    "University of Massachusetts - Dartmouth (MA)"
    "University of Massachusetts - Lowell (MA)"
    "University of Medicine and Dentistry of New Jersey (NJ)"
    "University of Memphis (TN)"
    "University of Miami (FL)"
    "University of Michigan - Ann Arbor (MI)"
    "University of Michigan - Dearborn (MI)"
    "University of Michigan - Flint (MI)"
    "University of Minnesota - Crookston (MN)"
    "University of Minnesota - Duluth (MN)"
    "University of Minnesota - Morris (MN)"
    "University of Minnesota - Twin Cities (MN)"
    "University of Mississippi (MS)"
    "University of Mississippi Medical Center (MS)"
    "University of Missouri (MO)"
    "University of Missouri - Kansas City (MO)"
    "University of Missouri - St. Louis (MO)"
    "University of Mobile (AL)"
    "University of Montana (MT)"
    "University of Montana - Western (MT)"
    "University of Montevallo (AL)"
    "University of Mount Union (OH)"
    "University of Nebraska Medical Center (NE)"
    "University of Nebraska - Kearney (NE)"
    "University of Nebraska - Lincoln (NE)"
    "University of Nebraska - Omaha (NE)"
    "University of Nevada - Las Vegas (NV)"
    "University of Nevada - Reno (NV)"
    "University of New Brunswick (None)"
    "University of New England (ME)"
    "University of New Hampshire (NH)"
    "University of New Haven (CT)"
    "University of New Mexico (NM)"
    "University of New Orleans (LA)"
    "University of North Alabama (AL)"
    "University of North Carolina School of the Arts (NC)"
    "University of North Carolina - Asheville (NC)"
    "University of North Carolina - Chapel Hill (NC)"
    "University of North Carolina - Charlotte (NC)"
    "University of North Carolina - Greensboro (NC)"
    "University of North Carolina - Pembroke (NC)"
    "University of North Carolina - Wilmington (NC)"
    "University of North Dakota (ND)"
    "University of North Florida (FL)"
    "University of North Georgia (GA)"
    "University of North Texas (TX)"
    "University of Northern Colorado (CO)"
    "University of Northern Iowa (IA)"
    "University of Northwestern Ohio (OH)"
    "University of Northwestern - St. Paul (MN)"
    "University of Notre Dame (IN)"
    "University of Oklahoma (OK)"
    "University of Oregon (OR)"
    "University of Ottawa (None)"
    "University of Pennsylvania (PA)"
    "University of Phoenix (AZ)"
    "University of Pikeville (KY)"
    "University of Pittsburgh (PA)"
    "University of Portland (OR)"
    "University of Prince Edward Island (None)"
    "University of Puerto Rico - Aguadilla (PR)"
    "University of Puerto Rico - Arecibo (PR)"
    "University of Puerto Rico - Bayamon (PR)"
    "University of Puerto Rico - Cayey (PR)"
    "University of Puerto Rico - Humacao (PR)"
    "University of Puerto Rico - Mayaguez (PR)"
    "University of Puerto Rico - Medical Sciences Campus (PR)"
    "University of Puerto Rico - Ponce (PR)"
    "University of Puerto Rico - Rio Piedras (PR)"
    "University of Puget Sound (WA)"
    "University of Redlands (CA)"
    "University of Regina (None)"
    "University of Rhode Island (RI)"
    "University of Richmond (VA)"
    "University of Rio Grande (OH)"
    "University of Rochester (NY)"
    "University of San Diego (CA)"
    "University of San Francisco (CA)"
    "University of Saskatchewan (None)"
    "University of Science and Arts of Oklahoma (OK)"
    "University of Scranton (PA)"
    "University of Sioux Falls (SD)"
    "University of South Alabama (AL)"
    "University of South Carolina (SC)"
    "University of South Carolina - Aiken (SC)"
    "University of South Carolina - Beaufort (SC)"
    "University of South Carolina - Upstate (SC)"
    "University of South Dakota (SD)"
    "University of South Florida (FL)"
    "University of South Florida - St. Petersburg (FL)"
    "University of Southern California (CA)"
    "University of Southern Indiana (IN)"
    "University of Southern Maine (ME)"
    "University of Southern Mississippi (MS)"
    "University of St. Francis (IL)"
    "University of St. Francis (IN)"
    "University of St. Joseph (CT)"
    "University of St. Mary (KS)"
    "University of St. Thomas (MN)"
    "University of St. Thomas (TX)"
    "University of Tampa (FL)"
    "University of Tennessee (TN)"
    "University of Tennessee - Chattanooga (TN)"
    "University of Tennessee - Martin (TN)"
    "University of Texas Health Science Center - Houston (TX)"
    "University of Texas Health Science Center - San Antonio (TX)"
    "University of Texas Medical Branch - Galveston (TX)"
    "University of Texas of the Permian Basin (TX)"
    "University of Texas - Arlington (TX)"
    "University of Texas - Austin (TX)"
    "University of Texas - Brownsville (TX)"
    "University of Texas - Dallas (TX)"
    "University of Texas - El Paso (TX)"
    "University of Texas - Pan American (TX)"
    "University of Texas - San Antonio (TX)"
    "University of Texas - Tyler (TX)"
    "University of the Arts (PA)"
    "University of the Cumberlands (KY)"
    "University of the District of Columbia (DC)"
    "University of the Incarnate Word (TX)"
    "University of the Ozarks (AR)"
    "University of the Pacific (CA)"
    "University of the Sacred Heart (PR)"
    "University of the Sciences (PA)"
    "University of the Southwest (NM)"
    "University of the Virgin Islands (VI)"
    "University of the West (CA)"
    "University of Toledo (OH)"
    "University of Toronto (None)"
    "University of Tulsa (OK)"
    "University of Utah (UT)"
    "University of Vermont (VT)"
    "University of Victoria (None)"
    "University of Virginia (VA)"
    "University of Virginia - Wise (VA)"
    "University of Washington (WA)"
    "University of Waterloo (None)"
    "University of West Alabama (AL)"
    "University of West Florida (FL)"
    "University of West Georgia (GA)"
    "University of Windsor (None)"
    "University of Winnipeg (None)"
    "University of Wisconsin - Eau Claire (WI)"
    "University of Wisconsin - Green Bay (WI)"
    "University of Wisconsin - La Crosse (WI)"
    "University of Wisconsin - Madison (WI)"
    "University of Wisconsin - Milwaukee (WI)"
    "University of Wisconsin - Oshkosh (WI)"
    "University of Wisconsin - Parkside (WI)"
    "University of Wisconsin - Platteville (WI)"
    "University of Wisconsin - River Falls (WI)"
    "University of Wisconsin - Stevens Point (WI)"
    "University of Wisconsin - Stout (WI)"
    "University of Wisconsin - Superior (WI)"
    "University of Wisconsin - Whitewater (WI)"
    "University of Wyoming (WY)"
    "Upper Iowa University (IA)"
    "Urbana University (OH)"
    "Ursinus College (PA)"
    "Ursuline College (OH)"
    "Utah State University (UT)"
    "Utah Valley University (UT)"
    "Utica College (NY)"
    "Valdosta State University (GA)"
    "Valley City State University (ND)"
    "Valley Forge Christian College (PA)"
    "Valparaiso University (IN)"
    "Vanderbilt University (TN)"
    "VanderCook College of Music (IL)"
    "Vanguard University of Southern California (CA)"
    "Vassar College (NY)"
    "Vaughn College of Aeronautics and Technology (NY)"
    "Vermont Technical College (VT)"
    "Victory University (TN)"
    "Villanova University (PA)"
    "Vincennes University (IN)"
    "Virginia Commonwealth University (VA)"
    "Virginia Intermont College (VA)"
    "Virginia Military Institute (VA)"
    "Virginia State University (VA)"
    "Virginia Tech (VA)"
    "Virginia Union University (VA)"
    "Virginia Wesleyan College (VA)"
    "Viterbo University (WI)"
    "Voorhees College (SC)"
    "Wabash College (IN)"
    "Wagner College (NY)"
    "Wake Forest University (NC)"
    "Walden University (MN)"
    "Waldorf College (IA)"
    "Walla Walla University (WA)"
    "Walsh College of Accountancy and Business Administration (MI)"
    "Walsh University (OH)"
    "Warner Pacific College (OR)"
    "Warner University (FL)"
    "Warren Wilson College (NC)"
    "Wartburg College (IA)"
    "Washburn University (KS)"
    "Washington Adventist University (MD)"
    "Washington and Jefferson College (PA)"
    "Washington and Lee University (VA)"
    "Washington College (MD)"
    "Washington State University (WA)"
    "Washington University in St. Louis (MO)"
    "Watkins College of Art, Design & Film (TN)"
    "Wayland Baptist University (TX)"
    "Wayne State College (NE)"
    "Wayne State University (MI)"
    "Waynesburg University (PA)"
    "Webb Institute (NY)"
    "Webber International University (FL)"
    "Weber State University (UT)"
    "Webster University (MO)"
    "Welch College (TN)"
    "Wellesley College (MA)"
    "Wells College (NY)"
    "Wentworth Institute of Technology (MA)"
    "Wesley College (DE)"
    "Wesleyan College (GA)"
    "Wesleyan University (CT)"
    "West Chester University of Pennsylvania (PA)"
    "West Liberty University (WV)"
    "West Texas A&M University (TX)"
    "West Virginia State University (WV)"
    "West Virginia University (WV)"
    "West Virginia University Institute of Technology (WV)"
    "West Virginia University - Parkersburg (WV)"
    "West Virginia Wesleyan College (WV)"
    "Western Carolina University (NC)"
    "Western Connecticut State University (CT)"
    "Western Governors University (UT)"
    "Western Illinois University (IL)"
    "Western International University (AZ)"
    "Western Kentucky University (KY)"
    "Western Michigan University (MI)"
    "Western Nevada College (NV)"
    "Western New England University (MA)"
    "Western New Mexico University (NM)"
    "Western Oregon University (OR)"
    "Western State Colorado University (CO)"
    "Western University (None)"
    "Western Washington University (WA)"
    "Westfield State University (MA)"
    "Westminster College (MO)"
    "Westminster College (PA)"
    "Westminster College (UT)"
    "Westmont College (CA)"
    "Wheaton College (IL)"
    "Wheaton College (MA)"
    "Wheeling Jesuit University (WV)"
    "Wheelock College (MA)"
    "Whitman College (WA)"
    "Whittier College (CA)"
    "Whitworth University (WA)"
    "Wichita State University (KS)"
    "Widener University (PA)"
    "Wilberforce University (OH)"
    "Wiley College (TX)"
    "Wilkes University (PA)"
    "Willamette University (OR)"
    "William Carey University (MS)"
    "William Jessup University (CA)"
    "William Jewell College (MO)"
    "William Paterson University of New Jersey (NJ)"
    "William Peace University (NC)"
    "William Penn University (IA)"
    "William Woods University (MO)"
    "Williams Baptist College (AR)"
    "Williams College (MA)"
    "Wilmington College (OH)"
    "Wilmington University (DE)"
    "Wilson College (PA)"
    "Wingate University (NC)"
    "Winona State University (MN)"
    "Winston-Salem State University (NC)"
    "Winthrop University (SC)"
    "Wisconsin Lutheran College (WI)"
    "Wittenberg University (OH)"
    "Wofford College (SC)"
    "Woodbury University (CA)"
    "Worcester Polytechnic Institute (MA)"
    "Worcester State University (MA)"
    "Wright State University (OH)"
    "Xavier University (OH)"
    "Xavier University of Louisiana (LA)"
    "Yale University (CT)"
    "Yeshiva University (NY)"
    "York College (NE)"
    "York College of Pennsylvania (PA)"
    "York University (None)"
    "Youngstown State University (OH)"
]
